//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.GIArkivValidator.WebAPI.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KS.GIArkivValidator.WebAPI.Validation.Resources.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig filformat på payload: {0}.
        /// </summary>
        public static string InvalidPayloadFileFormatMessage {
            get {
                return ResourceManager.GetString("InvalidPayloadFileFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fant ikke attributt {0} på node {1}.
        /// </summary>
        public static string MissingAttributeOnPayloadElement {
            get {
                return ResourceManager.GetString("MissingAttributeOnPayloadElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fant ingen forekomster av {0} i svarmeldingens innhold.
        /// </summary>
        public static string MissingPayloadElement {
            get {
                return ResourceManager.GetString("MissingPayloadElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangler innhold i svarmelding: {0}.
        /// </summary>
        public static string MissingPayloadFileMessage {
            get {
                return ResourceManager.GetString("MissingPayloadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manglende svarmelding: {0}.
        /// </summary>
        public static string MissingResponseMessage {
            get {
                return ResourceManager.GetString("MissingResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml-node {0} har ingen verdi.
        /// </summary>
        public static string MissingValueOnPayloadElement {
            get {
                return ResourceManager.GetString("MissingValueOnPayloadElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uventet innhold i svarmelding: {0}.
        /// </summary>
        public static string UnexpectedPayloadFileMessage {
            get {
                return ResourceManager.GetString("UnexpectedPayloadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uventet svarmelding: {0}.
        /// </summary>
        public static string UnexpectedResponseMessage {
            get {
                return ResourceManager.GetString("UnexpectedResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml-node {0} var forventet med verdi {1}, men {2} ble funnet.
        /// </summary>
        public static string WrongValueOnPayloadElement {
            get {
                return ResourceManager.GetString("WrongValueOnPayloadElement", resourceCulture);
            }
        }
    }
}
